#(c) 2020, Vadim Pavlov, ioc2rpz(at)gmail.com
version: '3'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "853:853/tcp"
      - "443:443/tcp"
    volumes:
      - /opt/b1tdc_doh_data/ssl:/etc/nginx/ssl
      - /opt/b1tdc_doh_data/nginx.conf:/etc/nginx/nginx.conf:ro
      - /opt/b1tdc_doh_data/users.passwd:/etc/nginx/users.passwd:ro
      - /opt/b1tdc_doh_data/njs.d:/etc/nginx/njs.d:ro
      - /opt/b1tdc_doh_data/nginx_log:/var/log/nginx/
    restart: always
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

