version: '3'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "853:853/tcp"
      - "443:443/tcp"
    volumes:
      - /opt/b1tdc_doh_data/ssl:/etc/nginx/ssl
      - /opt/b1tdc_doh_data/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
    logging:
      driver: syslog
    network_mode: "bridge"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'
#$ROOT_HOST
#$DOMAIN

# pull files via scp and key based auth
#/etc/nginx/ssl/certs/doh.pem
#/etc/nginx/ssl/private/doh.pem
# if ! cmp -s /etc/letsencrypt/live/$DOHDOMAIN/fullchain.pem $DOH_ROOT/ssl/doh.crt; then cp /etc/letsencrypt/live/$HOST/fullchain.pem $DOH_ROOT/ssl/doh.crt && cp /etc/letsencrypt/live/$DOHDOMAIN/privkey.pem $DOH_ROOT/ssl/doh.key && killall -9 doh-server; fi
# reload in the loop but for the first time we start nginx in foreground
# 
