#(c) 2020, Vadim Pavlov, ioc2rpz(at)gmail.com
version: '3'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "853:853/tcp"
      - "443:443/tcp"
    volumes:
      - /opt/b1tdc_doh_data/ssl:/etc/nginx/ssl:ro
      - /opt/b1tdc_doh_data/nginx.conf:/etc/nginx/nginx.conf:ro
      - /opt/b1tdc_doh_data/users.passwd:/etc/nginx/users.passwd:ro
      - /opt/b1tdc_doh_data/njs.d:/etc/nginx/njs.d:ro
      - /opt/b1tdc_doh_data/nginx_log:/var/log/nginx/
    restart: always
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/dns-route53
    volumes:
      - /opt/b1tdc_doh_data/certbot/conf:/etc/letsencrypt
      - /opt/b1tdc_doh_data/ssl:/opt/b1tdc_doh_data/ssl
      - /opt/b1tdc_doh_data/certbot_log:/var/log/letsencrypt
    restart: always
    environment:
      - DOHDOMAIN
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    entrypoint: "/bin/sh -c 'trap exit TERM;if [ ! -f /opt/b1tdc_doh_data/ssl/certs/doh.pem ]; then echo \"creating new certs for $DOHDOMAIN\";certbot certonly --agree-tos --email $EMAIL --dns-route53 --dns-route53-propagation-seconds 30 -d $DOHDOMAIN -d \"*.$DOHDOMAIN\"; cp /etc/letsencrypt/live/$DOHDOMAIN/fullchain.pem /opt/b1tdc_doh_data/ssl/certs/doh.pem && cp /etc/letsencrypt/live/$DOHDOMAIN/privkey.pem /etc/nginx/ssl/private/doh.pem; chmod 644 /opt/b1tdc_doh_data/ssl/private/doh.pem; fi; while :; do certbot renew --dns-route53 --dns-route53-propagation-seconds 30 && if ! cmp -s /etc/letsencrypt/live/$DOHDOMAIN/fullchain.pem /opt/b1tdc_doh_data/ssl/certs/doh.pem; then cp /etc/letsencrypt/live/$DOHDOMAIN/doh.pem /opt/b1tdc_doh_data/ssl/certs/doh.pem && cp /etc/letsencrypt/live/$DOHDOMAIN/privkey.pem /etc/nginx/ssl/private/doh.pem; chmod 644 /opt/b1tdc_doh_data/ssl/private/doh.pem; fi; sleep 12h & wait $${!}; done;'"